\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{flauros}[flauros]
\LoadClassWithOptions{beamer}

\RequirePackage{fontspec}
\RequirePackage{babel}
\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{amsthm}
\RequirePackage{float}
\RequirePackage{graphicx}
\RequirePackage{import}
\RequirePackage{tikz}
\RequirePackage{circuitikz}
\RequirePackage{listings}
\RequirePackage{siunitx}
\RequirePackage{esvect}
\RequirePackage{gensymb}

\usetheme[secheader]{Madrid}
\usecolortheme{orchid}
\useoutertheme{infolines}
\useinnertheme{rectangles}
\usefonttheme{professionalfonts}