\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{ippos}[ippos]
\LoadClassWithOptions{article}

\RequirePackage{fontspec}
\RequirePackage{babel}
\RequirePackage[toc, style=listhypergroup, nonumberlist, numberedsection, acronym, shortcuts]{glossaries}
\RequirePackage{glossaries-extra}
\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{amsthm}
\RequirePackage{float}
\RequirePackage{graphicx}
\RequirePackage{hyperref}
\RequirePackage{import}
