\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{melpo}[melpo]
\LoadClassWithOptions{book}

\RequirePackage{fontspec}
\RequirePackage{babel}
\RequirePackage[toc, style=listhypergroup, nonumberlist, numberedsection, acronym, shortcuts]{glossaries}
\RequirePackage{glossaries-extra}
\RequirePackage[nottoc]{tocbibind}
\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{amsthm}
\RequirePackage{caption}
\RequirePackage{circuitikz} % dessin elec avec tikz
\RequirePackage{enumitem}
\RequirePackage{esvect} % gestion vecteurs
\RequirePackage{etoc}
\RequirePackage{eurosym} % €
\RequirePackage{fancyhdr}
\RequirePackage{float}
\RequirePackage{flushend}
\RequirePackage{fontawesome} % icons font
\RequirePackage{gensymb}
\RequirePackage{graphicx}
\RequirePackage{hyperref}
\RequirePackage{import}
