\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{samyaza}[samyaza]
\LoadClassWithOptions{book}

\RequirePackage{fontspec}
\RequirePackage{babel}
\RequirePackage[toc, style=listhypergroup, nonumberlist, numberedsection, acronym, shortcuts]{glossaries}
\RequirePackage{glossaries-extra}
\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{amsthm}
\RequirePackage{float}
\RequirePackage{graphicx}
\RequirePackage{hyperref}
\RequirePackage{import}
\RequirePackage{tikz}
\RequirePackage{circuitikz}
\RequirePackage{listings}

\lstset{
	basicstyle=\footnotesize\ttfamily,
	breaklines=true
}